2794222 + 0 in total (QC-passed reads + QC-failed reads)
0 + 0 secondary
0 + 0 supplementary
0 + 0 duplicates
1296704 + 0 mapped (46.41%:N/A)
2794222 + 0 paired in sequencing
1397111 + 0 read1
1397111 + 0 read2
803878 + 0 properly paired (28.77%:N/A)
1015462 + 0 with itself and mate mapped
281242 + 0 singletons (10.07%:N/A)
174078 + 0 with mate mapped to a different chr
66077 + 0 with mate mapped to a different chr (mapQ>=5)
